-- -------------------------------------------------------------
--
-- Module: cic_decimator_10
--
-- Generated by MATLAB(R) 7.14 and the Filter Design HDL Coder 2.9.1.
--
-- Generated on: 2013-02-12 14:25:03
--
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- ClockEnableInputPort: clk_en
-- ResetInputPort: rst
-- Name: cic_decimator_10
-- TestBenchName: cic_decimator_10_tb
-- TestBenchStimulus: step ramp chirp noise 

-- Filter Specifications:
--
-- Sampling Frequency : N/A (normalized frequency)
-- Response           : CIC
-- Specification      : Fp,Ast
-- Multirate Type     : Decimator
-- Decimation Factor  : 10
-- Differential Delay : 1
-- Passband Edge      : 0.01
-- Stopband Atten.    : 60 dB
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Multirate Filter (real)
-- -----------------------------------------
-- Filter Structure        : Cascaded Integrator-Comb Decimator
-- Decimation Factor       : 10
-- Differential Delay      : 1
-- Number of Sections      : 3
-- Stable                  : Yes
-- Linear Phase            : Yes (Type 2)
--
-- Input                   : s10,9
-- Output                  : s10,-1
-- Filter Internals        : Minimum Word Lengths
--   Integrator Section 1  : s20,9
--   Integrator Section 2  : s17,6
--   Integrator Section 3  : s15,4
--   Comb Section 1        : s14,3
--   Comb Section 2        : s13,2
--   Comb Section 3        : s12,1
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;
ENTITY cic_decimator_10 IS
   PORT( clk                             :   IN    std_logic; 
         clk_en                          :   IN    std_logic; 
         rst                             :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(9 DOWNTO 0); -- sfix10_En9
         filter_out                      :   OUT   std_logic_vector(9 DOWNTO 0); -- sfix10_E1
         ce_out                          :   OUT   std_logic  
         );

END cic_decimator_10;


----------------------------------------------------------------
--Module Architecture: cic_decimator_10
----------------------------------------------------------------
ARCHITECTURE rtl OF cic_decimator_10 IS
  -- Local Functions
  -- Type Definitions
  -- Constants
  -- Signals
  SIGNAL cur_count                        : unsigned(3 DOWNTO 0); -- ufix4
  SIGNAL phase_1                          : std_logic; -- boolean
  SIGNAL ce_out_reg                       : std_logic; -- boolean
  --   
  SIGNAL input_register                   : signed(9 DOWNTO 0); -- sfix10_En9
  --   -- Section 1 Signals 
  SIGNAL section_in1                      : signed(9 DOWNTO 0); -- sfix10_En9
  SIGNAL section_cast1                    : signed(19 DOWNTO 0); -- sfix20_En9
  SIGNAL sum1                             : signed(19 DOWNTO 0); -- sfix20_En9
  SIGNAL section_out1                     : signed(19 DOWNTO 0); -- sfix20_En9
  SIGNAL add_cast                         : signed(19 DOWNTO 0); -- sfix20_En9
  SIGNAL add_cast_1                       : signed(19 DOWNTO 0); -- sfix20_En9
  SIGNAL add_temp                         : signed(20 DOWNTO 0); -- sfix21_En9
  --   -- Section 2 Signals 
  SIGNAL section_in2                      : signed(19 DOWNTO 0); -- sfix20_En9
  SIGNAL section_cast2                    : signed(16 DOWNTO 0); -- sfix17_En6
  SIGNAL sum2                             : signed(16 DOWNTO 0); -- sfix17_En6
  SIGNAL section_out2                     : signed(16 DOWNTO 0); -- sfix17_En6
  SIGNAL add_cast_2                       : signed(16 DOWNTO 0); -- sfix17_En6
  SIGNAL add_cast_3                       : signed(16 DOWNTO 0); -- sfix17_En6
  SIGNAL add_temp_1                       : signed(17 DOWNTO 0); -- sfix18_En6
  --   -- Section 3 Signals 
  SIGNAL section_in3                      : signed(16 DOWNTO 0); -- sfix17_En6
  SIGNAL section_cast3                    : signed(14 DOWNTO 0); -- sfix15_En4
  SIGNAL sum3                             : signed(14 DOWNTO 0); -- sfix15_En4
  SIGNAL section_out3                     : signed(14 DOWNTO 0); -- sfix15_En4
  SIGNAL add_cast_4                       : signed(14 DOWNTO 0); -- sfix15_En4
  SIGNAL add_cast_5                       : signed(14 DOWNTO 0); -- sfix15_En4
  SIGNAL add_temp_2                       : signed(15 DOWNTO 0); -- sfix16_En4
  --   -- Section 4 Signals 
  SIGNAL section_in4                      : signed(14 DOWNTO 0); -- sfix15_En4
  SIGNAL section_cast4                    : signed(13 DOWNTO 0); -- sfix14_En3
  SIGNAL diff1                            : signed(13 DOWNTO 0); -- sfix14_En3
  SIGNAL section_out4                     : signed(13 DOWNTO 0); -- sfix14_En3
  SIGNAL sub_cast                         : signed(13 DOWNTO 0); -- sfix14_En3
  SIGNAL sub_cast_1                       : signed(13 DOWNTO 0); -- sfix14_En3
  SIGNAL sub_temp                         : signed(14 DOWNTO 0); -- sfix15_En3
  --   -- Section 5 Signals 
  SIGNAL section_in5                      : signed(13 DOWNTO 0); -- sfix14_En3
  SIGNAL section_cast5                    : signed(12 DOWNTO 0); -- sfix13_En2
  SIGNAL diff2                            : signed(12 DOWNTO 0); -- sfix13_En2
  SIGNAL section_out5                     : signed(12 DOWNTO 0); -- sfix13_En2
  SIGNAL sub_cast_2                       : signed(12 DOWNTO 0); -- sfix13_En2
  SIGNAL sub_cast_3                       : signed(12 DOWNTO 0); -- sfix13_En2
  SIGNAL sub_temp_1                       : signed(13 DOWNTO 0); -- sfix14_En2
  --   -- Section 6 Signals 
  SIGNAL section_in6                      : signed(12 DOWNTO 0); -- sfix13_En2
  SIGNAL section_cast6                    : signed(11 DOWNTO 0); -- sfix12_En1
  SIGNAL diff3                            : signed(11 DOWNTO 0); -- sfix12_En1
  SIGNAL section_out6                     : signed(11 DOWNTO 0); -- sfix12_En1
  SIGNAL sub_cast_4                       : signed(11 DOWNTO 0); -- sfix12_En1
  SIGNAL sub_cast_5                       : signed(11 DOWNTO 0); -- sfix12_En1
  SIGNAL sub_temp_2                       : signed(12 DOWNTO 0); -- sfix13_En1
  SIGNAL output_typeconvert               : signed(9 DOWNTO 0); -- sfix10_E1
  --   
  SIGNAL output_register                  : signed(9 DOWNTO 0); -- sfix10_E1


BEGIN

  -- Block Statements
  --   ------------------ CE Output Generation ------------------

  ce_output : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      cur_count <= to_unsigned(0, 4);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_en = '1' THEN
        IF cur_count = to_unsigned(9, 4) THEN
          cur_count <= to_unsigned(0, 4);
        ELSE
          cur_count <= cur_count + 1;
        END IF;
      END IF;
    END IF; 
  END PROCESS ce_output;

  phase_1 <= '1' WHEN cur_count = to_unsigned(1, 4) AND clk_en = '1' ELSE '0';

  --   ------------------ CE Output Register ------------------

  ce_output_register : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      ce_out_reg <= '0';
    ELSIF clk'event AND clk = '1' THEN
      ce_out_reg <= phase_1;
      
    END IF; 
  END PROCESS ce_output_register;

  --   ------------------ Input Register ------------------

  input_reg_process : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      input_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_en = '1' THEN
        input_register <= signed(filter_in);
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  --   ------------------ Section # 1 : Integrator ------------------

  section_in1 <= input_register;

  section_cast1 <= resize(section_in1, 20);

  add_cast <= section_cast1;
  add_cast_1 <= section_out1;
  add_temp <= resize(add_cast, 21) + resize(add_cast_1, 21);
  sum1 <= add_temp(19 DOWNTO 0);

  integrator_delay_section1 : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      section_out1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_en = '1' THEN
        section_out1 <= sum1;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section1;

  --   ------------------ Section # 2 : Integrator ------------------

  section_in2 <= section_out1;

  section_cast2 <= section_in2(19 DOWNTO 3);

  add_cast_2 <= section_cast2;
  add_cast_3 <= section_out2;
  add_temp_1 <= resize(add_cast_2, 18) + resize(add_cast_3, 18);
  sum2 <= add_temp_1(16 DOWNTO 0);

  integrator_delay_section2 : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      section_out2 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_en = '1' THEN
        section_out2 <= sum2;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section2;

  --   ------------------ Section # 3 : Integrator ------------------

  section_in3 <= section_out2;

  section_cast3 <= section_in3(16 DOWNTO 2);

  add_cast_4 <= section_cast3;
  add_cast_5 <= section_out3;
  add_temp_2 <= resize(add_cast_4, 16) + resize(add_cast_5, 16);
  sum3 <= add_temp_2(14 DOWNTO 0);

  integrator_delay_section3 : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      section_out3 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_en = '1' THEN
        section_out3 <= sum3;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section3;

  --   ------------------ Section # 4 : Comb ------------------

  section_in4 <= section_out3;

  section_cast4 <= section_in4(14 DOWNTO 1);

  sub_cast <= section_cast4;
  sub_cast_1 <= diff1;
  sub_temp <= resize(sub_cast, 15) - resize(sub_cast_1, 15);
  section_out4 <= sub_temp(13 DOWNTO 0);

  comb_delay_section4 : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      diff1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_1 = '1' THEN
        diff1 <= section_cast4;
      END IF;
    END IF; 
  END PROCESS comb_delay_section4;

  --   ------------------ Section # 5 : Comb ------------------

  section_in5 <= section_out4;

  section_cast5 <= section_in5(13 DOWNTO 1);

  sub_cast_2 <= section_cast5;
  sub_cast_3 <= diff2;
  sub_temp_1 <= resize(sub_cast_2, 14) - resize(sub_cast_3, 14);
  section_out5 <= sub_temp_1(12 DOWNTO 0);

  comb_delay_section5 : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      diff2 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_1 = '1' THEN
        diff2 <= section_cast5;
      END IF;
    END IF; 
  END PROCESS comb_delay_section5;

  --   ------------------ Section # 6 : Comb ------------------

  section_in6 <= section_out5;

  section_cast6 <= section_in6(12 DOWNTO 1);

  sub_cast_4 <= section_cast6;
  sub_cast_5 <= diff3;
  sub_temp_2 <= resize(sub_cast_4, 13) - resize(sub_cast_5, 13);
  section_out6 <= sub_temp_2(11 DOWNTO 0);

  comb_delay_section6 : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      diff3 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_1 = '1' THEN
        diff3 <= section_cast6;
      END IF;
    END IF; 
  END PROCESS comb_delay_section6;

  output_typeconvert <= section_out6(11 DOWNTO 2);

  --   ------------------ Output Register ------------------

  output_reg_process : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_1 = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS output_reg_process;

  -- Assignment Statements
  ce_out <= ce_out_reg;
  filter_out <= std_logic_vector(output_register);
END rtl;
