-- ***************************************************************************************
-- File components.vhd auto-generated by packaging utiltiy on Mon Jun 18 18:08:41 2007 GMT
-- ***************************************************************************************

library ieee;
use ieee.std_logic_1164.all;

package components is
component CORESPI 
generic (
-- master+slave	: set USE_MASTER=1, USE_SLAVE=1 (default)
-- master only	: set USE_MASTER=1, USE_SLAVE=0
-- slave only	: set USE_MASTER=0, USE_SLAVE=1
FAMILY                  : integer := 17;
USE_MASTER		: integer := 1;
USE_SLAVE		: integer := 1
);
port (
PCLK			:	in	std_logic;	-- Global clock
PRESETN			:	in	std_logic;	-- Act.low asynchronous reset
-- SPI interface signals
m_sck			:	out	std_logic;	-- SPI master generated Serial Clock
m_miso			:	in	std_logic;	-- SPI serial data (master in/slave out)
m_mosi			:	out	std_logic;	-- SPI serial data (master out/slave in)
-- SPI master generated slave select lines
m_ss			:	out	std_logic_vector(7 downto 0);
s_sck			:	in	std_logic;	-- SPI slave, Serial Clock input
s_miso			:	out	std_logic;	-- SPI serial data (master in/slave out)
s_mosi			:	in	std_logic;	-- SPI serial data (master out/slave in)
s_ss			:	in	std_logic;	-- SPI slave, act.low slave select input
enable_master	        :	out	std_logic;	-- CoreSPI operating in master mode
enable_slave	        :	out	std_logic;	-- CoreSPI operating in slave mode
-- generic microcontroller interface signals
PWDATA			:	in	std_logic_vector(7 downto 0);	-- APB write data
PRDATA	        	:	out	std_logic_vector(7 downto 0);	-- APB read data
PADDR			:	in	std_logic_vector(3 downto 0);	-- APB Address
PENABLE			:	in	std_logic;	-- APB Enable
PSEL			:	in	std_logic;	-- APB Select
PWRITE			:	in	std_logic;	-- APB Write enable
interrupt		:	out	std_logic;	-- Masked interrupt output
-- Unmasked interrupt outputs
tx_reg_empty	        :	out	std_logic;	-- transmit register empty
rx_data_ready	        :	out	std_logic	-- data received and ready to be read
);
end component;

end components;