% AC

% S_AC = solve(...
%     '(U_1 - U_in)/R_in + U_1/R_p2 + U_1/R_p1 + U_1/R_5 + (U_1 - phi)/R_1 = 0', ...
%     '(phi - U_1)/R_1 + (phi - U_3)/R_3 = 0', ...
%     '(phi - U_2)/R_2 + (phi - U_4)/R_4 = 0', ...
%     '(U_2 - phi)/R_2 + U_2/R_6 = 0', ...
%     'U_3 + U_4 = 2*UCM', ...
%     '(U_in - U_1)/R_in = I_in', ...    
%     'R_1 = R_2', ...
%     'R_3 = R_4', ...
%     'UCM = 0', ...
%     'U_1', 'phi', 'U_2', 'U_3', 'U_4', 'R_2', 'R_4', 'UCM', 'I_in' );


node_eq1 = sym('(U_1 - U_in)/R_in + U_1/R_p2 + U_1/R_p1 + U_1/R_5 + (U_1 - phi)/R_1 = 0');
node_eq1_DC = sym('U_1/R_5 + (U_1 - phi)/R_1 = 0');
node_eq2 = sym('(phi - U_1)/R_1 + (phi - U_3)/R_3 = 0');
node_eq3 = sym('(phi - U_2)/R_2 + (phi - U_4)/R_4 = 0');
node_eq4 = sym('(U_2 - phi)/R_2 + U_2/R_6 = 0');
node_eq5 = sym('U_3 + U_4 = 2*UCM');
node_eq6 = sym('(U_in - U_1)/R_in = I_in');
node_eq7 = sym('R_1 = R_2');
node_eq8 = sym('R_3 = R_4');

UCM_val = 0;
UCM_val_DC = 3.3/2;
R_p1_val = 50;
R_p2_val = 1038;
R_in_val = 42.11;
U_in_val = 3.1;
R_5_val = 9.83e3;
R_6_val = R_5_val;
I_in_val = 0.035;
U_4_val = 0.512;


S_AC = solve(...
    node_eq1, ...
    node_eq2, ...
    node_eq3, ...
    node_eq4, ...
    node_eq5, ...
    node_eq6, ...
    node_eq7, ...
    node_eq8, ...
    sym(['UCM = ' num2str(UCM_val)]), ...
    sym(['R_p1 = ' num2str(R_p1_val)]), ...
    sym(['R_p2 = ' num2str(R_p2_val)]), ...
    sym(['R_in = ' num2str(R_in_val)]), ...
    sym(['U_in = ' num2str(U_in_val)]), ...
    sym(['R_5 = ' num2str(R_5_val)]), ...
    sym(['R_6 = ' num2str(R_6_val)]), ...
    sym(['I_in = ' num2str(I_in_val)]), ...
    sym(['U_4 = ' num2str(U_4_val)]), ...
    'U_1', 'phi', 'U_2', 'U_3', 'U_4', 'R_2', 'R_4', 'UCM', 'R_p1', 'R_p2', 'R_in', 'U_in', 'R_5', 'R_6', 'R_1', 'R_3', 'I_in' );

figure;
plot([0 S_AC.R_1 S_AC.R_1+S_AC.R_3 ], [S_AC.U_1 S_AC.phi S_AC.U_3], '.-', [-S_AC.R_6 0 S_AC.R_1 S_AC.R_1+S_AC.R_3 ], [0 S_AC.U_2 S_AC.phi S_AC.U_4], '.-' )

S_AC2 = solve(...
    node_eq1, ...
    node_eq2, ...
    node_eq3, ...
    node_eq4, ...
    node_eq5, ...
    node_eq6, ...
    node_eq7, ...
    node_eq8, ...
    sym(['UCM = ' num2str(UCM_val)]), ...
    sym(['R_p1 = ' num2str(R_p1_val)]), ...
    sym(['R_p2 = ' num2str(R_p2_val)]), ...
    sym(['R_in = ' num2str(R_in_val)]), ...
    sym(['R_5 = ' num2str(R_5_val)]), ...
    sym(['R_6 = ' num2str(R_6_val)]), ...
    sym(['R_1 = ' num2str(eval(S_AC.R_1))]), ...
    sym(['R_3 = ' num2str(eval(S_AC.R_3))]), ...
    'U_1', 'phi', 'U_2', 'U_3', 'U_4', 'R_2', 'R_4', 'UCM', 'R_p1', 'R_p2', 'R_in', 'R_5', 'R_6', 'I_in', 'R_1', 'R_3' );

figure;
ezplot(S_AC2.I_in, [-3.3, 3.3]);

% S_AC = solve(...
%     '(U_1 - U_in)/R_e + (U_1 - phi)/R_1 = 0', ...
%     '(phi - U_1)/R_1 + (phi - U_3)/R_3 = 0', ...
%     '(phi - U_2)/R_2 + (phi - U_4)/R_4 = 0', ...
%     '(U_2 - phi)/R_2 + U_2/R_6 = 0', ...
%     'U_3 + U_4 = 2*UCM', ...
%     'R_1 = R_2', ...
%     'R_3 = R_4', ...
%     'UCM = 0', ...
%     'R_p1 = 50', ...
%     'R_p2 = 1038', ...
%     'R_e = 22.37', ...
%     'U_in = 3', ...
%     'R_5 = 1e4', ...
%     'R_6 = 100', ...
%     '(U_in - U_1)/R_e = 0.035', ...
%     'U_4 = 0.5', ...
%     'U_1', 'phi', 'U_2', 'U_3', 'U_4', 'R_2', 'R_4', 'UCM', 'R_p1', 'R_p2', 'R_e', 'U_in', 'R_5', 'R_6', 'R_1', 'R_3' );


%figure;
%plot([-S_AC.R_e 0 S_AC.R_1 S_AC.R_1+S_AC.R_3 ], [S_AC.U_in S_AC.U_1 S_AC.phi S_AC.U_3], '.-', [-S_AC.R_6 0 S_AC.R_1 S_AC.R_1+S_AC.R_3 ], [0 S_AC.U_2 S_AC.phi S_AC.U_4], '.-' )

%DC

S_DC = solve(...
    node_eq1_DC, ...
    node_eq2, ...
    node_eq3, ...
    node_eq4, ...
    node_eq5, ...
    node_eq7, ...
    node_eq8, ...
    sym(['UCM = ' num2str(UCM_val_DC)]), ...
    sym(['R_5 = ' num2str(R_5_val)]), ...
    sym(['R_6 = ' num2str(R_6_val)]), ...
    sym(['R_1 = ' num2str(eval(S_AC.R_1))]), ...
    sym(['R_3 = ' num2str(eval(S_AC.R_3))]), ...
    'U_1', 'phi', 'U_2', 'U_3', 'U_4', 'R_2', 'R_4', 'UCM', 'R_5', 'R_6', 'R_1', 'R_3');


figure;
plot([0 S_AC.R_1 S_AC.R_1+S_AC.R_3 ], [S_DC.U_1 S_DC.phi S_DC.U_3], '.-', [-S_AC.R_6 0 S_AC.R_1 S_AC.R_1+S_AC.R_3 ], [0 S_DC.U_2 S_DC.phi S_DC.U_4], '.-' )

figure;
plot([0 S_AC.R_1 S_AC.R_1+S_AC.R_3 ], [S_DC.U_1 S_DC.phi S_DC.U_3]+[S_AC.U_1 S_AC.phi S_AC.U_3], 'r.-', [-S_AC.R_6 0 S_AC.R_1 S_AC.R_1+S_AC.R_3 ], [0 S_DC.U_2 S_DC.phi S_DC.U_4]+[0 S_AC.U_2 S_AC.phi S_AC.U_4], 'b.-', [0 S_AC.R_1 S_AC.R_1+S_AC.R_3 ], [S_DC.U_1 S_DC.phi S_DC.U_3]-[S_AC.U_1 S_AC.phi S_AC.U_3], 'r.-', [-S_AC.R_6 0 S_AC.R_1 S_AC.R_1+S_AC.R_3 ], [0 S_DC.U_2 S_DC.phi S_DC.U_4]-[0 S_AC.U_2 S_AC.phi S_AC.U_4], 'b.-' )

display(['R1: ' num2str(eval(S_AC.R_1))]);
display(['R3: ' num2str(eval(S_AC.R_3))]);
display(['R1/R3: ' num2str(eval(S_AC.R_1)/eval(S_AC.R_3)*100)]);

%actual values

R_1_val = 1580;
R_3_val = 1300;
display(['R1: ' num2str(R_1_val)]);
display(['R3: ' num2str(R_3_val)]);
display(['R1/R3: ' num2str(R_1_val/R_3_val*100)]);

S_AC3 = solve(...
    node_eq1, ...
    node_eq2, ...
    node_eq3, ...
    node_eq4, ...
    node_eq5, ...
    node_eq6, ...
    node_eq7, ...
    node_eq8, ...
    sym(['UCM = ' num2str(UCM_val)]), ...
    sym(['R_p1 = ' num2str(R_p1_val)]), ...
    sym(['R_p2 = ' num2str(R_p2_val)]), ...
    sym(['R_in = ' num2str(R_in_val)]), ...
    sym(['R_5 = ' num2str(R_5_val)]), ...
    sym(['R_6 = ' num2str(R_6_val)]), ...
    sym(['R_1 = ' num2str(R_1_val)]), ...
    sym(['R_3 = ' num2str(R_3_val)]), ...
    sym(['U_in = ' num2str(U_in_val)]), ...
    'U_1', 'phi', 'U_2', 'U_3', 'U_4', 'R_2', 'R_4', 'UCM', 'R_p1', 'R_p2', 'R_in', 'R_5', 'R_6', 'I_in', 'R_1', 'R_3', 'U_in' );

display(['U4: ' num2str(eval(S_AC3.U_4))]);
display(['Iin: ' num2str(eval(S_AC3.I_in))]);
display(['phi: ' num2str(eval(S_AC3.phi))]);
