% S = solve(...
%     '(U_2 - phi)/R_2 + U_2/R_6 = 0', ...
%     'phi' );
% 
% 
% S = solve(...
%     '(phi - U_2)/R_2 + (phi - U_4)/R_4 = 0', ...
%     '(U_2 - phi)/R_2 + U_2/R_6 = 0', ...
%     'phi', 'U_4' );
% 
% 
% S = solve(...
%     '(phi - U_2)/R_2 + (phi - U_4)/R_4 = 0', ...
%     '(U_2 - phi)/R_2 + U_2/R_6 = 0', ...
%     'U_3 + U_4 = 2*UCM', ...
%     'phi', 'U_4', 'U_3' );
% 
% 
% 
% S = solve(...
%     '(phi - U_2)/R_2 + (phi - U_4)/R_4 = 0', ...
%     '(U_2 - phi)/R_2 + U_2/R_6 = 0', ...
%     'U_3 + U_4 = 2*UCM', ...
%     '(phi - U_1)/R_1 + (phi - U_3)/R_3 = 0', ...
%     'phi', 'U_4', 'U_3', 'U_1' );
% 
% 

S = solve(...
    '-I_i + (U_1 - phi)/R_1 = 0', ...
    '(phi - U_1)/R_1 + (phi - U_3)/R_3 = 0', ...
    '(phi - U_2)/R_2 + (phi - U_4)/R_4 = 0', ...
    '(U_2 - phi)/R_2 + U_2/R_6 = 0', ...
    'U_3 + U_4 = 2*UCM', ...
    'R_i = U_1 / I_i', ...
    'I_i', 'phi', 'U_2', 'U_3', 'U_4', 'R_i' );

R_spec1 = subs(S.R_i, 'R_2', 'R_1');
R_spec2 = subs(R_spec1, 'R_3', 'R_4');
R_spec3 = subs(R_spec2, 'R_6', '0');
R_spec4 = subs(R_spec3, 'R_3', 'R_1');
R_spec5 = subs(R_spec4, 'R_1', '348');
R_spec6 = subs(R_spec5, 'UCM', '3.3/2');

%R_spec6 = subs(R_spec5, 'U_1', '3.3/2');

R_5 = sym('R_5');

R_parh = R_spec6 * R_5 / (R_spec6 + R_5);
R_spec7 = subs(R_parh, 'R_5', '1');

figure;
ezplot(R_spec7, [-3.3, 3.3]);


