-- -------------------------------------------------------------
--
-- Module: H_cic_dec
--
-- Generated by MATLAB(R) 7.14 and the Filter Design HDL Coder 2.9.1.
--
-- Generated on: 2012-11-24 16:58:37
--
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- ClockEnableInputPort: clk_en
-- ResetInputPort: rst
-- UseRisingEdge: on
-- TargetDirectory: D:\firmware\MainBoard\SdrReference\hdl
-- Name: H_cic_dec
-- TestBenchName: H_cic_dec_tb
-- TestBenchStimulus: step ramp chirp noise 

-- Filter Specifications:
--
-- Sampling Frequency : 20 MHz
-- Response           : CIC
-- Specification      : Fp,Ast
-- Multirate Type     : Decimator
-- Decimation Factor  : 20
-- Differential Delay : 1
-- Passband Edge      : 300 kHz
-- Stopband Atten.    : 20 dB
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Multirate Filter (real)
-- -----------------------------------------
-- Filter Structure        : Cascaded Integrator-Comb Decimator
-- Decimation Factor       : 20
-- Differential Delay      : 1
-- Number of Sections      : 3
-- Stable                  : Yes
-- Linear Phase            : Yes (Type 2)
--
-- Input                   : s10,9
-- Output                  : s16,2
-- Filter Internals        : Minimum Word Lengths
--   Integrator Section 1  : s23,9
--   Integrator Section 2  : s23,9
--   Integrator Section 3  : s21,7
--   Comb Section 1        : s20,6
--   Comb Section 2        : s19,5
--   Comb Section 3        : s18,4
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;
ENTITY H_cic_dec IS
   PORT( clk                             :   IN    std_logic; 
         clk_en                          :   IN    std_logic; 
         rst                             :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(9 DOWNTO 0); -- sfix10_En9
         filter_out                      :   OUT   std_logic_vector(15 DOWNTO 0); -- sfix16_En2
         ce_out                          :   OUT   std_logic  
         );

END H_cic_dec;


----------------------------------------------------------------
--Module Architecture: H_cic_dec
----------------------------------------------------------------
ARCHITECTURE rtl OF H_cic_dec IS
  -- Local Functions
  -- Type Definitions
  -- Constants
  -- Signals
  SIGNAL cur_count                        : unsigned(4 DOWNTO 0); -- ufix5
  SIGNAL phase_1                          : std_logic; -- boolean
  SIGNAL ce_out_reg                       : std_logic; -- boolean
  --   
  SIGNAL input_register                   : signed(9 DOWNTO 0); -- sfix10_En9
  --   -- Section 1 Signals 
  SIGNAL section_in1                      : signed(9 DOWNTO 0); -- sfix10_En9
  SIGNAL section_cast1                    : signed(22 DOWNTO 0); -- sfix23_En9
  SIGNAL sum1                             : signed(22 DOWNTO 0); -- sfix23_En9
  SIGNAL section_out1                     : signed(22 DOWNTO 0); -- sfix23_En9
  SIGNAL add_cast                         : signed(22 DOWNTO 0); -- sfix23_En9
  SIGNAL add_cast_1                       : signed(22 DOWNTO 0); -- sfix23_En9
  SIGNAL add_temp                         : signed(23 DOWNTO 0); -- sfix24_En9
  --   -- Section 2 Signals 
  SIGNAL section_in2                      : signed(22 DOWNTO 0); -- sfix23_En9
  SIGNAL sum2                             : signed(22 DOWNTO 0); -- sfix23_En9
  SIGNAL section_out2                     : signed(22 DOWNTO 0); -- sfix23_En9
  SIGNAL add_cast_2                       : signed(22 DOWNTO 0); -- sfix23_En9
  SIGNAL add_cast_3                       : signed(22 DOWNTO 0); -- sfix23_En9
  SIGNAL add_temp_1                       : signed(23 DOWNTO 0); -- sfix24_En9
  --   -- Section 3 Signals 
  SIGNAL section_in3                      : signed(22 DOWNTO 0); -- sfix23_En9
  SIGNAL section_cast3                    : signed(20 DOWNTO 0); -- sfix21_En7
  SIGNAL sum3                             : signed(20 DOWNTO 0); -- sfix21_En7
  SIGNAL section_out3                     : signed(20 DOWNTO 0); -- sfix21_En7
  SIGNAL add_cast_4                       : signed(20 DOWNTO 0); -- sfix21_En7
  SIGNAL add_cast_5                       : signed(20 DOWNTO 0); -- sfix21_En7
  SIGNAL add_temp_2                       : signed(21 DOWNTO 0); -- sfix22_En7
  --   -- Section 4 Signals 
  SIGNAL section_in4                      : signed(20 DOWNTO 0); -- sfix21_En7
  SIGNAL section_cast4                    : signed(19 DOWNTO 0); -- sfix20_En6
  SIGNAL diff1                            : signed(19 DOWNTO 0); -- sfix20_En6
  SIGNAL section_out4                     : signed(19 DOWNTO 0); -- sfix20_En6
  SIGNAL sub_cast                         : signed(19 DOWNTO 0); -- sfix20_En6
  SIGNAL sub_cast_1                       : signed(19 DOWNTO 0); -- sfix20_En6
  SIGNAL sub_temp                         : signed(20 DOWNTO 0); -- sfix21_En6
  --   -- Section 5 Signals 
  SIGNAL section_in5                      : signed(19 DOWNTO 0); -- sfix20_En6
  SIGNAL section_cast5                    : signed(18 DOWNTO 0); -- sfix19_En5
  SIGNAL diff2                            : signed(18 DOWNTO 0); -- sfix19_En5
  SIGNAL section_out5                     : signed(18 DOWNTO 0); -- sfix19_En5
  SIGNAL sub_cast_2                       : signed(18 DOWNTO 0); -- sfix19_En5
  SIGNAL sub_cast_3                       : signed(18 DOWNTO 0); -- sfix19_En5
  SIGNAL sub_temp_1                       : signed(19 DOWNTO 0); -- sfix20_En5
  --   -- Section 6 Signals 
  SIGNAL section_in6                      : signed(18 DOWNTO 0); -- sfix19_En5
  SIGNAL section_cast6                    : signed(17 DOWNTO 0); -- sfix18_En4
  SIGNAL diff3                            : signed(17 DOWNTO 0); -- sfix18_En4
  SIGNAL section_out6                     : signed(17 DOWNTO 0); -- sfix18_En4
  SIGNAL sub_cast_4                       : signed(17 DOWNTO 0); -- sfix18_En4
  SIGNAL sub_cast_5                       : signed(17 DOWNTO 0); -- sfix18_En4
  SIGNAL sub_temp_2                       : signed(18 DOWNTO 0); -- sfix19_En4
  SIGNAL output_typeconvert               : signed(15 DOWNTO 0); -- sfix16_En2
  --   
  SIGNAL output_register                  : signed(15 DOWNTO 0); -- sfix16_En2


BEGIN

  -- Block Statements
  --   ------------------ CE Output Generation ------------------

  ce_output : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      cur_count <= to_unsigned(0, 5);
    ELSIF rising_edge(clk) THEN
      IF clk_en = '1' THEN
        IF cur_count = to_unsigned(19, 5) THEN
          cur_count <= to_unsigned(0, 5);
        ELSE
          cur_count <= cur_count + 1;
        END IF;
      END IF;
    END IF; 
  END PROCESS ce_output;

  phase_1 <= '1' WHEN cur_count = to_unsigned(1, 5) AND clk_en = '1' ELSE '0';

  --   ------------------ CE Output Register ------------------

  ce_output_register : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      ce_out_reg <= '0';
    ELSIF rising_edge(clk) THEN
      ce_out_reg <= phase_1;
      
    END IF; 
  END PROCESS ce_output_register;

  --   ------------------ Input Register ------------------

  input_reg_process : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      input_register <= (OTHERS => '0');
    ELSIF rising_edge(clk) THEN
      IF clk_en = '1' THEN
        input_register <= signed(filter_in);
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  --   ------------------ Section # 1 : Integrator ------------------

  section_in1 <= input_register;

  section_cast1 <= resize(section_in1, 23);

  add_cast <= section_cast1;
  add_cast_1 <= section_out1;
  add_temp <= resize(add_cast, 24) + resize(add_cast_1, 24);
  sum1 <= add_temp(22 DOWNTO 0);

  integrator_delay_section1 : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      section_out1 <= (OTHERS => '0');
    ELSIF rising_edge(clk) THEN
      IF clk_en = '1' THEN
        section_out1 <= sum1;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section1;

  --   ------------------ Section # 2 : Integrator ------------------

  section_in2 <= section_out1;

  add_cast_2 <= section_in2;
  add_cast_3 <= section_out2;
  add_temp_1 <= resize(add_cast_2, 24) + resize(add_cast_3, 24);
  sum2 <= add_temp_1(22 DOWNTO 0);

  integrator_delay_section2 : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      section_out2 <= (OTHERS => '0');
    ELSIF rising_edge(clk) THEN
      IF clk_en = '1' THEN
        section_out2 <= sum2;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section2;

  --   ------------------ Section # 3 : Integrator ------------------

  section_in3 <= section_out2;

  section_cast3 <= section_in3(22 DOWNTO 2);

  add_cast_4 <= section_cast3;
  add_cast_5 <= section_out3;
  add_temp_2 <= resize(add_cast_4, 22) + resize(add_cast_5, 22);
  sum3 <= add_temp_2(20 DOWNTO 0);

  integrator_delay_section3 : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      section_out3 <= (OTHERS => '0');
    ELSIF rising_edge(clk) THEN
      IF clk_en = '1' THEN
        section_out3 <= sum3;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section3;

  --   ------------------ Section # 4 : Comb ------------------

  section_in4 <= section_out3;

  section_cast4 <= section_in4(20 DOWNTO 1);

  sub_cast <= section_cast4;
  sub_cast_1 <= diff1;
  sub_temp <= resize(sub_cast, 21) - resize(sub_cast_1, 21);
  section_out4 <= sub_temp(19 DOWNTO 0);

  comb_delay_section4 : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      diff1 <= (OTHERS => '0');
    ELSIF rising_edge(clk) THEN
      IF phase_1 = '1' THEN
        diff1 <= section_cast4;
      END IF;
    END IF; 
  END PROCESS comb_delay_section4;

  --   ------------------ Section # 5 : Comb ------------------

  section_in5 <= section_out4;

  section_cast5 <= section_in5(19 DOWNTO 1);

  sub_cast_2 <= section_cast5;
  sub_cast_3 <= diff2;
  sub_temp_1 <= resize(sub_cast_2, 20) - resize(sub_cast_3, 20);
  section_out5 <= sub_temp_1(18 DOWNTO 0);

  comb_delay_section5 : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      diff2 <= (OTHERS => '0');
    ELSIF rising_edge(clk) THEN
      IF phase_1 = '1' THEN
        diff2 <= section_cast5;
      END IF;
    END IF; 
  END PROCESS comb_delay_section5;

  --   ------------------ Section # 6 : Comb ------------------

  section_in6 <= section_out5;

  section_cast6 <= section_in6(18 DOWNTO 1);

  sub_cast_4 <= section_cast6;
  sub_cast_5 <= diff3;
  sub_temp_2 <= resize(sub_cast_4, 19) - resize(sub_cast_5, 19);
  section_out6 <= sub_temp_2(17 DOWNTO 0);

  comb_delay_section6 : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      diff3 <= (OTHERS => '0');
    ELSIF rising_edge(clk) THEN
      IF phase_1 = '1' THEN
        diff3 <= section_cast6;
      END IF;
    END IF; 
  END PROCESS comb_delay_section6;

  output_typeconvert <= section_out6(17 DOWNTO 2);

  --   ------------------ Output Register ------------------

  output_reg_process : PROCESS (clk, rst)
  BEGIN
    IF rst = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF rising_edge(clk) THEN
      IF phase_1 = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS output_reg_process;

  -- Assignment Statements
  ce_out <= ce_out_reg;
  filter_out <= std_logic_vector(output_register);
END rtl;
